/*
Copyright 2021 The Pixiu Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	imagesetv1alpha1 "github.com/caoyingjunz/pixiu/pkg/apis/imageset/v1alpha1"
	versioned "github.com/caoyingjunz/pixiu/pkg/client/clientset/versioned"
	internalinterfaces "github.com/caoyingjunz/pixiu/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/caoyingjunz/pixiu/pkg/client/listers/imageset/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ImageSetInformer provides access to a shared informer and lister for
// ImageSets.
type ImageSetInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ImageSetLister
}

type imageSetInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewImageSetInformer constructs a new informer for ImageSet type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewImageSetInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredImageSetInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredImageSetInformer constructs a new informer for ImageSet type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredImageSetInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AppsV1alpha1().ImageSets(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AppsV1alpha1().ImageSets(namespace).Watch(context.TODO(), options)
			},
		},
		&imagesetv1alpha1.ImageSet{},
		resyncPeriod,
		indexers,
	)
}

func (f *imageSetInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredImageSetInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *imageSetInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&imagesetv1alpha1.ImageSet{}, f.defaultInformer)
}

func (f *imageSetInformer) Lister() v1alpha1.ImageSetLister {
	return v1alpha1.NewImageSetLister(f.Informer().GetIndexer())
}
