/*
Copyright 2021 The Pixiu Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/caoyingjunz/pixiu/pkg/apis/apps/v1alpha1"
	scheme "github.com/caoyingjunz/pixiu/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AdvancedImagesGetter has a method to return a AdvancedImageInterface.
// A group's client should implement this interface.
type AdvancedImagesGetter interface {
	AdvancedImages(namespace string) AdvancedImageInterface
}

// AdvancedImageInterface has methods to work with AdvancedImage resources.
type AdvancedImageInterface interface {
	Create(ctx context.Context, advancedImage *v1alpha1.AdvancedImage, opts v1.CreateOptions) (*v1alpha1.AdvancedImage, error)
	Update(ctx context.Context, advancedImage *v1alpha1.AdvancedImage, opts v1.UpdateOptions) (*v1alpha1.AdvancedImage, error)
	UpdateStatus(ctx context.Context, advancedImage *v1alpha1.AdvancedImage, opts v1.UpdateOptions) (*v1alpha1.AdvancedImage, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.AdvancedImage, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.AdvancedImageList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AdvancedImage, err error)
	AdvancedImageExpansion
}

// advancedImages implements AdvancedImageInterface
type advancedImages struct {
	client rest.Interface
	ns     string
}

// newAdvancedImages returns a AdvancedImages
func newAdvancedImages(c *AppsV1alpha1Client, namespace string) *advancedImages {
	return &advancedImages{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the advancedImage, and returns the corresponding advancedImage object, and an error if there is any.
func (c *advancedImages) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AdvancedImage, err error) {
	result = &v1alpha1.AdvancedImage{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("advancedimages").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AdvancedImages that match those selectors.
func (c *advancedImages) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AdvancedImageList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.AdvancedImageList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("advancedimages").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested advancedImages.
func (c *advancedImages) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("advancedimages").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a advancedImage and creates it.  Returns the server's representation of the advancedImage, and an error, if there is any.
func (c *advancedImages) Create(ctx context.Context, advancedImage *v1alpha1.AdvancedImage, opts v1.CreateOptions) (result *v1alpha1.AdvancedImage, err error) {
	result = &v1alpha1.AdvancedImage{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("advancedimages").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(advancedImage).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a advancedImage and updates it. Returns the server's representation of the advancedImage, and an error, if there is any.
func (c *advancedImages) Update(ctx context.Context, advancedImage *v1alpha1.AdvancedImage, opts v1.UpdateOptions) (result *v1alpha1.AdvancedImage, err error) {
	result = &v1alpha1.AdvancedImage{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("advancedimages").
		Name(advancedImage.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(advancedImage).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *advancedImages) UpdateStatus(ctx context.Context, advancedImage *v1alpha1.AdvancedImage, opts v1.UpdateOptions) (result *v1alpha1.AdvancedImage, err error) {
	result = &v1alpha1.AdvancedImage{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("advancedimages").
		Name(advancedImage.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(advancedImage).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the advancedImage and deletes it. Returns an error if one occurs.
func (c *advancedImages) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("advancedimages").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *advancedImages) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("advancedimages").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched advancedImage.
func (c *advancedImages) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AdvancedImage, err error) {
	result = &v1alpha1.AdvancedImage{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("advancedimages").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
