/*
Copyright 2021 The Caoyingjunz Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/caoyingjunz/csi-driver-localstorage/pkg/apis/localstorage/v1"
	scheme "github.com/caoyingjunz/csi-driver-localstorage/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// LocalStoragesGetter has a method to return a LocalStorageInterface.
// A group's client should implement this interface.
type LocalStoragesGetter interface {
	LocalStorages() LocalStorageInterface
}

// LocalStorageInterface has methods to work with LocalStorage resources.
type LocalStorageInterface interface {
	Create(ctx context.Context, localStorage *v1.LocalStorage, opts metav1.CreateOptions) (*v1.LocalStorage, error)
	Update(ctx context.Context, localStorage *v1.LocalStorage, opts metav1.UpdateOptions) (*v1.LocalStorage, error)
	UpdateStatus(ctx context.Context, localStorage *v1.LocalStorage, opts metav1.UpdateOptions) (*v1.LocalStorage, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.LocalStorage, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.LocalStorageList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.LocalStorage, err error)
	LocalStorageExpansion
}

// localStorages implements LocalStorageInterface
type localStorages struct {
	client rest.Interface
}

// newLocalStorages returns a LocalStorages
func newLocalStorages(c *StorageV1Client) *localStorages {
	return &localStorages{
		client: c.RESTClient(),
	}
}

// Get takes name of the localStorage, and returns the corresponding localStorage object, and an error if there is any.
func (c *localStorages) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.LocalStorage, err error) {
	result = &v1.LocalStorage{}
	err = c.client.Get().
		Resource("localstorages").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of LocalStorages that match those selectors.
func (c *localStorages) List(ctx context.Context, opts metav1.ListOptions) (result *v1.LocalStorageList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.LocalStorageList{}
	err = c.client.Get().
		Resource("localstorages").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested localStorages.
func (c *localStorages) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("localstorages").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a localStorage and creates it.  Returns the server's representation of the localStorage, and an error, if there is any.
func (c *localStorages) Create(ctx context.Context, localStorage *v1.LocalStorage, opts metav1.CreateOptions) (result *v1.LocalStorage, err error) {
	result = &v1.LocalStorage{}
	err = c.client.Post().
		Resource("localstorages").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(localStorage).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a localStorage and updates it. Returns the server's representation of the localStorage, and an error, if there is any.
func (c *localStorages) Update(ctx context.Context, localStorage *v1.LocalStorage, opts metav1.UpdateOptions) (result *v1.LocalStorage, err error) {
	result = &v1.LocalStorage{}
	err = c.client.Put().
		Resource("localstorages").
		Name(localStorage.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(localStorage).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *localStorages) UpdateStatus(ctx context.Context, localStorage *v1.LocalStorage, opts metav1.UpdateOptions) (result *v1.LocalStorage, err error) {
	result = &v1.LocalStorage{}
	err = c.client.Put().
		Resource("localstorages").
		Name(localStorage.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(localStorage).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the localStorage and deletes it. Returns an error if one occurs.
func (c *localStorages) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("localstorages").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *localStorages) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("localstorages").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched localStorage.
func (c *localStorages) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.LocalStorage, err error) {
	result = &v1.LocalStorage{}
	err = c.client.Patch(pt).
		Resource("localstorages").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
