{
 "title": "localstorage_controller  dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "localstorage_controller_volumes_total",
   "type": "stat",
   "description": "volumes total",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(localstorage_controller_volumes_total)",
     "legendFormat": "sum"
    },
    {
     "expr": "localstorage_controller_volumes_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "localstorage_controller_volume_size sum",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(localstorage_controller_volume_size)",
     "legendFormat": "sum"
    },
    {
     "expr": "sum(localstorage_controller_volume_size) by (instance)",
     "legendFormat": "sum_by({{instance}})"
    }
   ]
  },
  {
   "title": "localstorage_controller_volume_size detail",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "localstorage_controller_volume_size"
    }
   ]
  }
 ]
}