global:
  scrape_interval: 10s # sampling period
  evaluation_interval: 10s # Alarm rule calculation period

scrape_configs:
  - job_name: 'localstorage_controller'
    static_configs:
      - targets: [ '<pixiu-ls-controller>:10259' ] # 10259 is metrics port